[tool.poetry]
name = "test_timer"
version = "0.1.0"
description = ""
authors = ["nazrul <mnazrul.c@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools>=42",
    "wheel"
]
build-backend = "poetry.core.masonry.api"
